// Auto-generated scripts loading header file
#include "camera.cscript"
#include "flashlight.cscript"
#include "free_camera.cscript"
#include "helice.cscript"
#include "level_editor.cscript"
#include "menu.cscript"
#include "pinball.cscript"
#include "player.cscript"
#include "settings.cscript"
#include "test.cscript"
#include "title_screen.cscript"
#include "twomp.cscript"
