// Auto-generated scripts loading header file
#include "../__processed__/src/scripts/camera.cscript"
#include "../__processed__/src/scripts/flashlight.cscript"
#include "../__processed__/src/scripts/free_camera.cscript"
#include "../__processed__/src/scripts/level_editor.cscript"
#include "../__processed__/src/scripts/menu.cscript"
#include "../__processed__/src/scripts/pinball.cscript"
#include "../__processed__/src/scripts/player.cscript"
#include "../__processed__/src/scripts/settings.cscript"
#include "../__processed__/src/scripts/title_screen.cscript"
