enum CollisionsCode {
    CTEST_BOX_WITH_BOX              = NODE_BOX_CSHAPE | NODE_BOX_CSHAPE << 8,
    CTEST_BOX_WITH_SPHERE           = NODE_BOX_CSHAPE | NODE_SPHERE_CSHAPE << 8,
    CTEST_BOX_WITH_PLANE            = NODE_BOX_CSHAPE | NODE_PLANE_CSHAPE << 8,
    CTEST_SPHERE_WITH_SPHERE        = NODE_SPHERE_CSHAPE | NODE_SPHERE_CSHAPE << 8,
    CTEST_SPHERE_WITH_PLANE         = NODE_SPHERE_CSHAPE | NODE_PLANE_CSHAPE << 8,
    CTEST_PLANE_WITH_PLANE          = NODE_PLANE_CSHAPE | NODE_PLANE_CSHAPE << 8,
};