enum CollisionsCode {
    CTEST_BOX_WITH_BOX              = CLASS_TYPE_BOXCSHAPE | CLASS_TYPE_BOXCSHAPE << 8,
    CTEST_BOX_WITH_SPHERE           = CLASS_TYPE_BOXCSHAPE | CLASS_TYPE_SPHERECSHAPE << 8,
    CTEST_BOX_WITH_PLANE            = CLASS_TYPE_BOXCSHAPE | CLASS_TYPE_PLANECSHAPE << 8,
    CTEST_SPHERE_WITH_SPHERE        = CLASS_TYPE_SPHERECSHAPE | CLASS_TYPE_SPHERECSHAPE << 8,
    CTEST_SPHERE_WITH_PLANE         = CLASS_TYPE_SPHERECSHAPE | CLASS_TYPE_PLANECSHAPE << 8,
    CTEST_PLANE_WITH_PLANE          = CLASS_TYPE_PLANECSHAPE | CLASS_TYPE_PLANECSHAPE << 8,
};