// This file is generated by the class_tools.c tool
#include "__processed__/node.class.h"
#include "__processed__/nodes_camera.class.h"
#include "__processed__/nodes_cshapes_box_cshape.class.h"
#include "__processed__/nodes_cshapes_capsule_cshape.class.h"
#include "__processed__/nodes_cshapes_cshape.class.h"
#include "__processed__/nodes_cshapes_mesh_cshape.class.h"
#include "__processed__/nodes_cshapes_plane_cshape.class.h"
#include "__processed__/nodes_cshapes_ray_cshape.class.h"
#include "__processed__/nodes_cshapes_sphere_cshape.class.h"
#include "__processed__/nodes_framebuffer.class.h"
#include "__processed__/nodes_frames_button.class.h"
#include "__processed__/nodes_frames_checkbox.class.h"
#include "__processed__/nodes_frames_control_frame.class.h"
#include "__processed__/nodes_frames_frame.class.h"
#include "__processed__/nodes_frames_image_frame.class.h"
#include "__processed__/nodes_frames_input_area.class.h"
#include "__processed__/nodes_frames_label.class.h"
#include "__processed__/nodes_frames_radiobutton.class.h"
#include "__processed__/nodes_frames_selectlist.class.h"
#include "__processed__/nodes_lights_directional_light.class.h"
#include "__processed__/nodes_lights_light.class.h"
#include "__processed__/nodes_lights_point_light.class.h"
#include "__processed__/nodes_lights_spot_light.class.h"
#include "__processed__/nodes_mesh.class.h"
#include "__processed__/nodes_model.class.h"
#include "__processed__/nodes_physics_area.class.h"
#include "__processed__/nodes_physics_bodies_body.class.h"
#include "__processed__/nodes_physics_bodies_kinematic_body.class.h"
#include "__processed__/nodes_physics_bodies_rigid_body.class.h"
#include "__processed__/nodes_physics_bodies_static_body.class.h"
#include "__processed__/nodes_physics_physical_node.class.h"
#include "__processed__/nodes_scene.class.h"
#include "__processed__/nodes_skybox.class.h"
#include "__processed__/nodes_texture.class.h"
#include "__processed__/nodes_textured_mesh.class.h"
#ifndef IMPORT_CLASS_H
#define IMPORT_CLASS_H
typedef enum ClassType {
	CLASS_TYPE_NODE,
	CLASS_TYPE_CAMERA,
	CLASS_TYPE_BOXCSHAPE,
	CLASS_TYPE_CAPSULECSHAPE,
	CLASS_TYPE_CSHAPE,
	CLASS_TYPE_MESHCSHAPE,
	CLASS_TYPE_PLANECSHAPE,
	CLASS_TYPE_RAYCSHAPE,
	CLASS_TYPE_SPHERECSHAPE,
	CLASS_TYPE_FRAMEBUFFER,
	CLASS_TYPE_BUTTON,
	CLASS_TYPE_CHECKBOX,
	CLASS_TYPE_CONTROLFRAME,
	CLASS_TYPE_FRAME,
	CLASS_TYPE_IMAGEFRAME,
	CLASS_TYPE_INPUTAREA,
	CLASS_TYPE_LABEL,
	CLASS_TYPE_RADIOBUTTON,
	CLASS_TYPE_SELECTLIST,
	CLASS_TYPE_DIRECTIONALLIGHT,
	CLASS_TYPE_LIGHT,
	CLASS_TYPE_POINTLIGHT,
	CLASS_TYPE_SPOTLIGHT,
	CLASS_TYPE_MESH,
	CLASS_TYPE_MODEL,
	CLASS_TYPE_AREA,
	CLASS_TYPE_BODY,
	CLASS_TYPE_KINEMATICBODY,
	CLASS_TYPE_RIGIDBODY,
	CLASS_TYPE_STATICBODY,
	CLASS_TYPE_PHYSICALNODE,
	CLASS_TYPE_SCENE,
	CLASS_TYPE_SKYBOX,
	CLASS_TYPE_TEXTURE,
	CLASS_TYPE_TEXTUREDMESH,
	CLASS_TYPE_COUNT
} ClassType;
struct MethodsCorrespondance {
	void (*constructor[35])(void * __retValueVP__, va_list args);
	void (*initialize_node[35])(void * __retValueVP__, va_list args);
	void (*get_glow_shader[35])(void * __retValueVP__, va_list args);
	void (*cast[35])(void * __retValueVP__, va_list args);
	void (*load[35])(void * __retValueVP__, va_list args);
	void (*save[35])(void * __retValueVP__, va_list args);
	void (*render[35])(void * __retValueVP__, va_list args);
	void (*update[35])(void * __retValueVP__, va_list args);
	void (*free[35])(void * __retValueVP__, va_list args);
	void (*is_cshape[35])(void * __retValueVP__, va_list args);
	void (*is_body[35])(void * __retValueVP__, va_list args);
	void (*is_area[35])(void * __retValueVP__, va_list args);
	void (*is_gui_element[35])(void * __retValueVP__, va_list args);
	void (*test_function[35])(void * __retValueVP__, va_list args);
	void (*get_priority[35])(void * __retValueVP__, va_list args);
	void (*get_vao[35])(void * __retValueVP__, va_list args);
	void (*init_button[35])(void * __retValueVP__, va_list args);
	void (*is_button[35])(void * __retValueVP__, va_list args);
	void (*is_checkbox[35])(void * __retValueVP__, va_list args);
	void (*handle_dimension_unit[35])(void * __retValueVP__, va_list args);
	void (*init_frame[35])(void * __retValueVP__, va_list args);
	void (*refresh[35])(void * __retValueVP__, va_list args);
	void (*refreshContent[35])(void * __retValueVP__, va_list args);
	void (*prepare_render[35])(void * __retValueVP__, va_list args);
	void (*draw_frame[35])(void * __retValueVP__, va_list args);
	void (*is_input_area[35])(void * __retValueVP__, va_list args);
	void (*is_selectlist[35])(void * __retValueVP__, va_list args);
	void (*is_radiobutton[35])(void * __retValueVP__, va_list args);
	void (*init_radiobutton[35])(void * __retValueVP__, va_list args);
	void (*refreshOptions[35])(void * __retValueVP__, va_list args);
	void (*init_light[35])(void * __retValueVP__, va_list args);
	void (*init_vao[35])(void * __retValueVP__, va_list args);
	void (*precompile_display_lists[35])(void * __retValueVP__, va_list args);
	void (*collect_node[35])(void * __retValueVP__, va_list args);
	void (*sort_nodes[35])(void * __retValueVP__, va_list args);
	void (*get_collisions_shapes[35])(void * __retValueVP__, va_list args);
	void (*get_node_collection[35])(void * __retValueVP__, va_list args);
	void (*apply_impulse[35])(void * __retValueVP__, va_list args);
	void (*get_length[35])(void * __retValueVP__, va_list args);
};
struct ClassManager {
	struct MethodsCorrespondance methodsCorrespondance;
	ClassType extends[35];
	const char * class_names[35];
};
extern const struct ClassManager classManager;
#define BUILD_CLASS_METHODS_CORRESPONDANCE(classManager) const struct ClassManager classManager = {\
	.methodsCorrespondance = {\
		.constructor = {__class_method_node_constructor, __class_method_camera_constructor, __class_method_boxcshape_constructor, __class_method_capsulecshape_constructor, __class_method_node_constructor, __class_method_meshcshape_constructor, __class_method_planecshape_constructor, __class_method_raycshape_constructor, __class_method_spherecshape_constructor, __class_method_framebuffer_constructor, __class_method_button_constructor, __class_method_checkbox_constructor, __class_method_controlframe_constructor, __class_method_frame_constructor, __class_method_imageframe_constructor, __class_method_inputarea_constructor, __class_method_label_constructor, __class_method_radiobutton_constructor, __class_method_selectlist_constructor, __class_method_directionallight_constructor, __class_method_node_constructor, __class_method_pointlight_constructor, __class_method_spotlight_constructor, __class_method_mesh_constructor, __class_method_model_constructor, __class_method_area_constructor, __class_method_node_constructor, __class_method_kinematicbody_constructor, __class_method_rigidbody_constructor, __class_method_staticbody_constructor, __class_method_node_constructor, __class_method_scene_constructor, __class_method_skybox_constructor, __class_method_texture_constructor, __class_method_texturedmesh_constructor},\
		.initialize_node = {__class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node, __class_method_node_initialize_node},\
		.get_glow_shader = {__class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader, __class_method_node_get_glow_shader},\
		.cast = {__class_method_node_cast, __class_method_camera_cast, __class_method_boxcshape_cast, __class_method_capsulecshape_cast, __class_method_node_cast, __class_method_meshcshape_cast, __class_method_planecshape_cast, __class_method_raycshape_cast, __class_method_spherecshape_cast, __class_method_framebuffer_cast, __class_method_button_cast, __class_method_checkbox_cast, __class_method_controlframe_cast, __class_method_frame_cast, __class_method_imageframe_cast, __class_method_inputarea_cast, __class_method_label_cast, __class_method_radiobutton_cast, __class_method_selectlist_cast, __class_method_directionallight_cast, __class_method_node_cast, __class_method_pointlight_cast, __class_method_spotlight_cast, __class_method_mesh_cast, __class_method_model_cast, __class_method_node_cast, __class_method_node_cast, __class_method_node_cast, __class_method_node_cast, __class_method_node_cast, __class_method_node_cast, __class_method_scene_cast, __class_method_skybox_cast, __class_method_texture_cast, __class_method_texturedmesh_cast},\
		.load = {__class_method_node_load, __class_method_camera_load, __class_method_boxcshape_load, __class_method_capsulecshape_load, __class_method_node_load, __class_method_meshcshape_load, __class_method_planecshape_load, __class_method_raycshape_load, __class_method_spherecshape_load, __class_method_framebuffer_load, __class_method_button_load, __class_method_checkbox_load, __class_method_controlframe_load, __class_method_frame_load, __class_method_imageframe_load, __class_method_inputarea_load, __class_method_label_load, __class_method_radiobutton_load, __class_method_selectlist_load, __class_method_directionallight_load, __class_method_node_load, __class_method_pointlight_load, __class_method_spotlight_load, __class_method_mesh_load, __class_method_model_load, __class_method_area_load, __class_method_node_load, __class_method_kinematicbody_load, __class_method_rigidbody_load, __class_method_staticbody_load, __class_method_node_load, __class_method_scene_load, __class_method_skybox_load, __class_method_texture_load, __class_method_texturedmesh_load},\
		.save = {__class_method_node_save, __class_method_camera_save, __class_method_boxcshape_save, __class_method_capsulecshape_save, __class_method_node_save, __class_method_meshcshape_save, __class_method_planecshape_save, __class_method_raycshape_save, __class_method_spherecshape_save, __class_method_framebuffer_save, __class_method_button_save, __class_method_checkbox_save, __class_method_controlframe_save, __class_method_frame_save, __class_method_imageframe_save, __class_method_inputarea_save, __class_method_label_save, __class_method_radiobutton_save, __class_method_selectlist_save, __class_method_directionallight_save, __class_method_node_save, __class_method_pointlight_save, __class_method_spotlight_save, __class_method_mesh_save, __class_method_model_save, __class_method_area_save, __class_method_node_save, __class_method_kinematicbody_save, __class_method_rigidbody_save, __class_method_staticbody_save, __class_method_node_save, __class_method_scene_save, __class_method_skybox_save, __class_method_texture_save, __class_method_texturedmesh_save},\
		.render = {__class_method_node_render, __class_method_node_render, __class_method_boxcshape_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_frame_render, __class_method_frame_render, __class_method_controlframe_render, __class_method_frame_render, __class_method_imageframe_render, __class_method_frame_render, __class_method_label_render, __class_method_frame_render, __class_method_frame_render, __class_method_light_render, __class_method_light_render, __class_method_light_render, __class_method_light_render, __class_method_mesh_render, __class_method_model_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_node_render, __class_method_scene_render, __class_method_skybox_render, __class_method_node_render, __class_method_texturedmesh_render},\
		.update = {__class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_button_update, __class_method_button_update, __class_method_frame_update, __class_method_frame_update, __class_method_frame_update, __class_method_inputarea_update, __class_method_frame_update, __class_method_button_update, __class_method_selectlist_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_area_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update, __class_method_node_update},\
		.free = {__class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_button_free, __class_method_checkbox_free, __class_method_frame_free, __class_method_frame_free, __class_method_imageframe_free, __class_method_inputarea_free, __class_method_label_free, __class_method_radiobutton_free, __class_method_selectlist_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_model_free, __class_method_physicalnode_free, __class_method_physicalnode_free, __class_method_physicalnode_free, __class_method_physicalnode_free, __class_method_physicalnode_free, __class_method_physicalnode_free, __class_method_node_free, __class_method_node_free, __class_method_node_free, __class_method_node_free},\
		.is_cshape = {__class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_cshape_is_cshape, __class_method_cshape_is_cshape, __class_method_cshape_is_cshape, __class_method_cshape_is_cshape, __class_method_cshape_is_cshape, __class_method_cshape_is_cshape, __class_method_cshape_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape, __class_method_node_is_cshape},\
		.is_body = {__class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_body_is_body, __class_method_body_is_body, __class_method_body_is_body, __class_method_body_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body, __class_method_node_is_body},\
		.is_area = {__class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_area_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area, __class_method_node_is_area},\
		.is_gui_element = {__class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element, __class_method_node_is_gui_element},\
		.test_function = {__class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function, __class_method_node_test_function},\
		.get_priority = {NULL, NULL, __class_method_boxcshape_get_priority, __class_method_capsulecshape_get_priority, NULL, __class_method_meshcshape_get_priority, __class_method_planecshape_get_priority, __class_method_raycshape_get_priority, __class_method_spherecshape_get_priority, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_vao = {NULL, NULL, __class_method_boxcshape_get_vao, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_get_vao, __class_method_frame_get_vao, __class_method_frame_get_vao, __class_method_frame_get_vao, __class_method_frame_get_vao, __class_method_frame_get_vao, __class_method_frame_get_vao, __class_method_frame_get_vao, __class_method_frame_get_vao, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.init_button = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_button_init_button, __class_method_button_init_button, NULL, NULL, NULL, NULL, NULL, __class_method_button_init_button, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_button = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_button_is_button, __class_method_button_is_button, __class_method_frame_is_button, __class_method_frame_is_button, __class_method_frame_is_button, __class_method_frame_is_button, __class_method_frame_is_button, __class_method_button_is_button, __class_method_frame_is_button, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_checkbox = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_checkbox, __class_method_checkbox_is_checkbox, __class_method_frame_is_checkbox, __class_method_frame_is_checkbox, __class_method_frame_is_checkbox, __class_method_frame_is_checkbox, __class_method_frame_is_checkbox, __class_method_frame_is_checkbox, __class_method_frame_is_checkbox, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.handle_dimension_unit = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.init_frame = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_init_frame, __class_method_frame_init_frame, __class_method_frame_init_frame, __class_method_frame_init_frame, __class_method_frame_init_frame, __class_method_frame_init_frame, __class_method_frame_init_frame, __class_method_frame_init_frame, __class_method_frame_init_frame, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.refresh = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_refresh, __class_method_frame_refresh, __class_method_frame_refresh, __class_method_frame_refresh, __class_method_frame_refresh, __class_method_inputarea_refresh, __class_method_label_refresh, __class_method_frame_refresh, __class_method_selectlist_refresh, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.refreshContent = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_refreshContent, __class_method_frame_refreshContent, __class_method_frame_refreshContent, __class_method_frame_refreshContent, __class_method_frame_refreshContent, __class_method_frame_refreshContent, __class_method_frame_refreshContent, __class_method_frame_refreshContent, __class_method_frame_refreshContent, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.prepare_render = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_prepare_render, __class_method_frame_prepare_render, __class_method_frame_prepare_render, __class_method_frame_prepare_render, __class_method_frame_prepare_render, __class_method_frame_prepare_render, __class_method_frame_prepare_render, __class_method_frame_prepare_render, __class_method_frame_prepare_render, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.draw_frame = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_draw_frame, __class_method_frame_draw_frame, __class_method_frame_draw_frame, __class_method_frame_draw_frame, __class_method_frame_draw_frame, __class_method_frame_draw_frame, __class_method_frame_draw_frame, __class_method_frame_draw_frame, __class_method_frame_draw_frame, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_input_area = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_input_area, __class_method_frame_is_input_area, __class_method_frame_is_input_area, __class_method_frame_is_input_area, __class_method_frame_is_input_area, __class_method_inputarea_is_input_area, __class_method_frame_is_input_area, __class_method_frame_is_input_area, __class_method_frame_is_input_area, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_selectlist = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_selectlist, __class_method_frame_is_selectlist, __class_method_frame_is_selectlist, __class_method_frame_is_selectlist, __class_method_frame_is_selectlist, __class_method_frame_is_selectlist, __class_method_frame_is_selectlist, __class_method_frame_is_selectlist, __class_method_selectlist_is_selectlist, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_radiobutton = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_radiobutton, __class_method_frame_is_radiobutton, __class_method_frame_is_radiobutton, __class_method_frame_is_radiobutton, __class_method_frame_is_radiobutton, __class_method_frame_is_radiobutton, __class_method_frame_is_radiobutton, __class_method_radiobutton_is_radiobutton, __class_method_frame_is_radiobutton, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.init_radiobutton = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_radiobutton_init_radiobutton, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.refreshOptions = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_selectlist_refreshOptions, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.init_light = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_light_init_light, __class_method_light_init_light, __class_method_light_init_light, __class_method_light_init_light, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.init_vao = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_light_init_vao, __class_method_light_init_vao, __class_method_light_init_vao, __class_method_light_init_vao, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.precompile_display_lists = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_model_precompile_display_lists, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.collect_node = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_collect_node, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.sort_nodes = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_sort_nodes, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_collisions_shapes = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_get_collisions_shapes, NULL, __class_method_kinematicbody_get_collisions_shapes, __class_method_rigidbody_get_collisions_shapes, __class_method_staticbody_get_collisions_shapes, NULL, NULL, NULL, NULL, NULL},\
		.get_node_collection = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_get_node_collection, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.apply_impulse = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_body_apply_impulse, __class_method_kinematicbody_apply_impulse, __class_method_rigidbody_apply_impulse, __class_method_body_apply_impulse, NULL, NULL, NULL, NULL, NULL},\
		.get_length = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_kinematicbody_get_length, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
	},\
	.extends = {-1, 0, 4, 4, 0, 4, 4, 4, 4, 0, 13, 10, 13, 0, 13, 13, 13, 10, 13, 20, 0, 20, 20, 0, 0, 30, 30, 26, 26, 26, 0, 0, 0, 0, 0},\
	.class_names = {"Node", "Camera", "BoxCShape", "CapsuleCShape", "CShape", "MeshCShape", "PlaneCShape", "RayCShape", "SphereCShape", "Framebuffer", "Button", "CheckBox", "ControlFrame", "Frame", "ImageFrame", "InputArea", "Label", "RadioButton", "SelectList", "DirectionalLight", "Light", "PointLight", "SpotLight", "Mesh", "Model", "Area", "Body", "KinematicBody", "RigidBody", "StaticBody", "PhysicalNode", "Scene", "Skybox", "Texture", "TexturedMesh"}\
};
#endif
