// This file is generated by the class_tools.c tool
#include "../__processed__/classes_node.class.h"
#include "../__processed__/classes_nodes_camera.class.h"
#include "../__processed__/classes_nodes_cshapes_box_cshape.class.h"
#include "../__processed__/classes_nodes_cshapes_capsule_cshape.class.h"
#include "../__processed__/classes_nodes_cshapes_cshape.class.h"
#include "../__processed__/classes_nodes_cshapes_mesh_cshape.class.h"
#include "../__processed__/classes_nodes_cshapes_plane_cshape.class.h"
#include "../__processed__/classes_nodes_cshapes_ray_cshape.class.h"
#include "../__processed__/classes_nodes_cshapes_sphere_cshape.class.h"
#include "../__processed__/classes_nodes_framebuffer.class.h"
#include "../__processed__/classes_nodes_frames_button.class.h"
#include "../__processed__/classes_nodes_frames_checkbox.class.h"
#include "../__processed__/classes_nodes_frames_control_frame.class.h"
#include "../__processed__/classes_nodes_frames_frame.class.h"
#include "../__processed__/classes_nodes_frames_image_frame.class.h"
#include "../__processed__/classes_nodes_frames_input_area.class.h"
#include "../__processed__/classes_nodes_frames_label.class.h"
#include "../__processed__/classes_nodes_frames_radiobutton.class.h"
#include "../__processed__/classes_nodes_frames_selectlist.class.h"
#include "../__processed__/classes_nodes_lights_directional_light.class.h"
#include "../__processed__/classes_nodes_lights_light.class.h"
#include "../__processed__/classes_nodes_lights_point_light.class.h"
#include "../__processed__/classes_nodes_lights_spot_light.class.h"
#include "../__processed__/classes_nodes_mesh.class.h"
#include "../__processed__/classes_nodes_model.class.h"
#include "../__processed__/classes_nodes_physics_area.class.h"
#include "../__processed__/classes_nodes_physics_bodies_body.class.h"
#include "../__processed__/classes_nodes_physics_bodies_kinematic_body.class.h"
#include "../__processed__/classes_nodes_physics_bodies_rigid_body.class.h"
#include "../__processed__/classes_nodes_physics_bodies_static_body.class.h"
#include "../__processed__/classes_nodes_physics_physical_node.class.h"
#include "../__processed__/classes_nodes_scene.class.h"
#include "../__processed__/classes_nodes_skybox.class.h"
#include "../__processed__/classes_nodes_texture.class.h"
#include "../__processed__/classes_nodes_textured_mesh.class.h"
#ifndef IMPORT_CLASS_H
#define IMPORT_CLASS_H
typedef enum ClassType {
	CLASS_TYPE_FOR,
	CLASS_TYPE_IS,
	CLASS_TYPE_AND,
	CLASS_TYPE_PROVIDES,
	CLASS_TYPE_CSHAPE,
	CLASS_TYPE_MESHCSHAPE,
	CLASS_TYPE_IS,
	CLASS_TYPE_RAYCSHAPE,
	CLASS_TYPE_SPHERECSHAPE,
	CLASS_TYPE_IMPLEMENTATION,
	CLASS_TYPE_AND,
	CLASS_TYPE_FOR,
	CLASS_TYPE_CONTROLFRAME,
	CLASS_TYPE_FRAME,
	CLASS_TYPE_PROVIDES,
	CLASS_TYPE_AND,
	CLASS_TYPE_AND,
	CLASS_TYPE_PROVIDES,
	CLASS_TYPE_SELECTLIST,
	CLASS_TYPE_USED,
	CLASS_TYPE_FOR,
	CLASS_TYPE_PROVIDES,
	CLASS_TYPE_PROVIDES,
	CLASS_TYPE_MESH,
	CLASS_TYPE_MODEL,
	CLASS_TYPE_AREA,
	CLASS_TYPE_FOR,
	CLASS_TYPE_KINEMATICBODY,
	CLASS_TYPE_RIGIDBODY,
	CLASS_TYPE_STATICBODY,
	CLASS_TYPE_PHYSICALNODE,
	CLASS_TYPE_SCENE,
	CLASS_TYPE_SKYBOX,
	CLASS_TYPE_TEXTURE,
	CLASS_TYPE_IS,
	CLASS_TYPE_COUNT
} ClassType;
struct MethodsCorrespondance {
	void (*is_cshape[35])(void * __retValueVP__, va_list args);
	void (*get_model[35])(void * __retValueVP__, va_list args);
	void (*get_shader[35])(void * __retValueVP__, va_list args);
	void (*render[35])(void * __retValueVP__, va_list args);
	void (*constructor[35])(void * __retValueVP__, va_list args);
	void (*get_priority[35])(void * __retValueVP__, va_list args);
	void (*load[35])(void * __retValueVP__, va_list args);
	void (*save[35])(void * __retValueVP__, va_list args);
	void (*handle_dimension_unit[35])(void * __retValueVP__, va_list args);
	void (*init_frame[35])(void * __retValueVP__, va_list args);
	void (*refresh[35])(void * __retValueVP__, va_list args);
	void (*refreshContent[35])(void * __retValueVP__, va_list args);
	void (*update[35])(void * __retValueVP__, va_list args);
	void (*draw_frame[35])(void * __retValueVP__, va_list args);
	void (*get_vao[35])(void * __retValueVP__, va_list args);
	void (*is_gui_element[35])(void * __retValueVP__, va_list args);
	void (*is_button[35])(void * __retValueVP__, va_list args);
	void (*is_input_area[35])(void * __retValueVP__, va_list args);
	void (*is_selectlist[35])(void * __retValueVP__, va_list args);
	void (*is_checkbox[35])(void * __retValueVP__, va_list args);
	void (*is_radiobutton[35])(void * __retValueVP__, va_list args);
	void (*free[35])(void * __retValueVP__, va_list args);
	void (*refreshOptions[35])(void * __retValueVP__, va_list args);
	void (*get_settings_data[35])(void * __retValueVP__, va_list args);
	void (*collect_node[35])(void * __retValueVP__, va_list args);
	void (*is_area[35])(void * __retValueVP__, va_list args);
	void (*sort_nodes[35])(void * __retValueVP__, va_list args);
	void (*get_collisions_shapes[35])(void * __retValueVP__, va_list args);
	void (*get_node_collection[35])(void * __retValueVP__, va_list args);
	void (*get_length[35])(void * __retValueVP__, va_list args);
	void (*apply_impulse[35])(void * __retValueVP__, va_list args);
	void (*get_velocity_norm[35])(void * __retValueVP__, va_list args);
	void (*get_velocity[35])(void * __retValueVP__, va_list args);
	void (*get_mass[35])(void * __retValueVP__, va_list args);
	void (*get_center_of_mass[35])(void * __retValueVP__, va_list args);
	void (*get_collision_normal[35])(void * __retValueVP__, va_list args);
	void (*load_cubemap[35])(void * __retValueVP__, va_list args);
	void (*create_skybox[35])(void * __retValueVP__, va_list args);
};
struct ClassManager {
	struct MethodsCorrespondance methodsCorrespondance;
	ClassType extends[35];
	const char * class_names[35];
};
extern const struct ClassManager classManager;
#define BUILD_CLASS_METHODS_CORRESPONDANCE(classManager) const struct ClassManager classManager = {\
	.methodsCorrespondance = {\
		.is_cshape = {NULL, NULL, NULL, NULL, __class_method_cshape_is_cshape, __class_method_cshape_is_cshape, NULL, __class_method_cshape_is_cshape, __class_method_cshape_is_cshape, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_model = {NULL, NULL, NULL, NULL, __class_method_cshape_get_model, __class_method_cshape_get_model, NULL, __class_method_cshape_get_model, __class_method_spherecshape_get_model, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_shader = {NULL, NULL, NULL, NULL, __class_method_cshape_get_shader, __class_method_cshape_get_shader, NULL, __class_method_cshape_get_shader, __class_method_cshape_get_shader, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.render = {NULL, NULL, NULL, NULL, __class_method_cshape_render, __class_method_cshape_render, NULL, __class_method_cshape_render, __class_method_cshape_render, NULL, NULL, NULL, __class_method_controlframe_render, __class_method_frame_render, NULL, NULL, NULL, NULL, __class_method_frame_render, NULL, NULL, NULL, NULL, __class_method_mesh_render, __class_method_model_render, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_scene_render, __class_method_skybox_render, NULL, NULL},\
		.constructor = {NULL, NULL, NULL, NULL, NULL, __class_method_meshcshape_constructor, NULL, __class_method_raycshape_constructor, __class_method_spherecshape_constructor, NULL, NULL, NULL, __class_method_controlframe_constructor, __class_method_frame_constructor, NULL, NULL, NULL, NULL, __class_method_selectlist_constructor, NULL, NULL, NULL, NULL, __class_method_mesh_constructor, __class_method_model_constructor, __class_method_area_constructor, NULL, __class_method_kinematicbody_constructor, __class_method_rigidbody_constructor, __class_method_staticbody_constructor, NULL, __class_method_scene_constructor, __class_method_skybox_constructor, __class_method_texture_constructor, NULL},\
		.get_priority = {NULL, NULL, NULL, NULL, NULL, __class_method_meshcshape_get_priority, NULL, __class_method_raycshape_get_priority, __class_method_spherecshape_get_priority, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.load = {NULL, NULL, NULL, NULL, NULL, __class_method_meshcshape_load, NULL, __class_method_raycshape_load, __class_method_spherecshape_load, NULL, NULL, NULL, __class_method_controlframe_load, __class_method_frame_load, NULL, NULL, NULL, NULL, __class_method_selectlist_load, NULL, NULL, NULL, NULL, __class_method_mesh_load, __class_method_model_load, __class_method_area_load, NULL, __class_method_kinematicbody_load, __class_method_rigidbody_load, __class_method_staticbody_load, NULL, __class_method_scene_load, __class_method_skybox_load, __class_method_texture_load, NULL},\
		.save = {NULL, NULL, NULL, NULL, NULL, __class_method_meshcshape_save, NULL, __class_method_raycshape_save, __class_method_spherecshape_save, NULL, NULL, NULL, __class_method_controlframe_save, __class_method_frame_save, NULL, NULL, NULL, NULL, __class_method_selectlist_save, NULL, NULL, NULL, NULL, __class_method_mesh_save, __class_method_model_save, __class_method_area_save, NULL, __class_method_kinematicbody_save, __class_method_rigidbody_save, __class_method_staticbody_save, NULL, __class_method_scene_save, __class_method_skybox_save, __class_method_texture_save, NULL},\
		.handle_dimension_unit = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_handle_dimension_unit, __class_method_frame_handle_dimension_unit, NULL, NULL, NULL, NULL, __class_method_frame_handle_dimension_unit, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.init_frame = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_init_frame, __class_method_frame_init_frame, NULL, NULL, NULL, NULL, __class_method_frame_init_frame, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.refresh = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_refresh, __class_method_frame_refresh, NULL, NULL, NULL, NULL, __class_method_selectlist_refresh, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.refreshContent = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_refreshContent, __class_method_frame_refreshContent, NULL, NULL, NULL, NULL, __class_method_frame_refreshContent, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.update = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_update, __class_method_frame_update, NULL, NULL, NULL, NULL, __class_method_selectlist_update, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_update, NULL, __class_method_kinematicbody_update, __class_method_rigidbody_update, __class_method_staticbody_update, NULL, NULL, NULL, NULL, NULL},\
		.draw_frame = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_draw_frame, __class_method_frame_draw_frame, NULL, NULL, NULL, NULL, __class_method_frame_draw_frame, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_vao = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_get_vao, __class_method_frame_get_vao, NULL, NULL, NULL, NULL, __class_method_frame_get_vao, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_gui_element = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_gui_element, __class_method_frame_is_gui_element, NULL, NULL, NULL, NULL, __class_method_frame_is_gui_element, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_button = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_button, __class_method_frame_is_button, NULL, NULL, NULL, NULL, __class_method_frame_is_button, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_input_area = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_input_area, __class_method_frame_is_input_area, NULL, NULL, NULL, NULL, __class_method_frame_is_input_area, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_selectlist = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_selectlist, __class_method_frame_is_selectlist, NULL, NULL, NULL, NULL, __class_method_selectlist_is_selectlist, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_checkbox = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_checkbox, __class_method_frame_is_checkbox, NULL, NULL, NULL, NULL, __class_method_frame_is_checkbox, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_radiobutton = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_is_radiobutton, __class_method_frame_is_radiobutton, NULL, NULL, NULL, NULL, __class_method_frame_is_radiobutton, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.free = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_frame_free, __class_method_frame_free, NULL, NULL, NULL, NULL, __class_method_selectlist_free, NULL, NULL, NULL, NULL, NULL, __class_method_model_free, __class_method_physicalnode_free, NULL, NULL, NULL, NULL, __class_method_physicalnode_free, NULL, NULL, NULL, NULL},\
		.refreshOptions = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_selectlist_refreshOptions, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_settings_data = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_model_get_settings_data, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.collect_node = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_collect_node, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.is_area = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_is_area, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.sort_nodes = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_sort_nodes, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_collisions_shapes = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_get_collisions_shapes, NULL, __class_method_kinematicbody_get_collisions_shapes, __class_method_rigidbody_get_collisions_shapes, __class_method_staticbody_get_collisions_shapes, NULL, NULL, NULL, NULL, NULL},\
		.get_node_collection = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_area_get_node_collection, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_length = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_kinematicbody_get_length, NULL, NULL, NULL, NULL, NULL, NULL, NULL},\
		.apply_impulse = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_kinematicbody_apply_impulse, __class_method_rigidbody_apply_impulse, NULL, NULL, NULL, NULL, NULL, NULL},\
		.get_velocity_norm = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_kinematicbody_get_velocity_norm, __class_method_rigidbody_get_velocity_norm, __class_method_staticbody_get_velocity_norm, NULL, NULL, NULL, NULL, NULL},\
		.get_velocity = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_kinematicbody_get_velocity, __class_method_rigidbody_get_velocity, __class_method_staticbody_get_velocity, NULL, NULL, NULL, NULL, NULL},\
		.get_mass = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_kinematicbody_get_mass, __class_method_rigidbody_get_mass, __class_method_staticbody_get_mass, NULL, NULL, NULL, NULL, NULL},\
		.get_center_of_mass = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_kinematicbody_get_center_of_mass, __class_method_rigidbody_get_center_of_mass, __class_method_staticbody_get_center_of_mass, NULL, NULL, NULL, NULL, NULL},\
		.get_collision_normal = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_staticbody_get_collision_normal, NULL, NULL, NULL, NULL, NULL},\
		.load_cubemap = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_skybox_load_cubemap, NULL, NULL},\
		.create_skybox = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, __class_method_skybox_create_skybox, NULL, NULL},\
	},\
	.extends = {-1, -1, -1, -1, -1, 4, -1, 4, 4, -1, -1, -1, 13, -1, -1, -1, -1, -1, 13, -1, -1, -1, -1, -1, -1, 30, -1, -1, -1, -1, -1, -1, -1, -1, -1},\
	.class_names = {"for", "is", "and", "provides", "CShape", "MeshCShape", "is", "RayCShape", "SphereCShape", "implementation", "and", "for", "ControlFrame", "Frame", "provides", "and", "and", "provides", "SelectList", "used", "for", "provides", "provides", "Mesh", "Model", "Area", "for", "KinematicBody", "RigidBody", "StaticBody", "PhysicalNode", "Scene", "Skybox", "Texture", "is"}\
};
#endif
